<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello in SMA-App</title>

    <style>

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            background-color: #3aabef;

        }

        a {

            margin-bottom: 50px;
            margin-top: 50px;
            display: block;
            text-align: center;
            text-transform: uppercase;
            text-decoration: none;
            font-size: 40px;
            color: white;
        }




    </style>
</head>
<body>

<a class="login" href="http://localhost:8080/googlelogin">Zaloguj</a>
<a class="logout" href="main">Start Bez Logowania</a>


</body>
</html>