<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello in SMA-App</title>

    <style>

      

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            background-color: #3aabef;

        }

     body {
         text-align: center;

     }

        a {
            background-color: skyblue;
            display: inline-block;
            margin: 100px auto;
            width: 500px;
            padding: 40px 40px;
            font-family: Arial,sans-serif;
            text-transform: uppercase;
            text-decoration: none;
            font-size: 30px;
            color: white;
        }
        a:hover{
            background-color: white;
            color: #3aabef;
        }


      img {
          display: block;
          margin: 0 auto;
          height: 300px;
          width: 300px;
      }





    </style>
</head>
<body>

<a class="login" href="http://localhost:8080/googlelogin">Zaloguj</a>
<a class="" href="http://localhost:8080/maps-stream">Start Bez Logowania</a>

<img src="https://thumbor.sd-cdn.fr/wtvqeXqkR0A7PMZrUt3h9Q9_DDU=/770x515/cdn.sd-cdn.fr/wp-content/uploads/2019/03/Twitter-logo-illustration.jpg" alt="">




</body>
</html>