<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello in SMA-App</title>

    <style>

      

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            background-color: #3aabef;

        }



        a {

            margin-bottom: 50px;
            margin-top: 50px;
            padding: 40px 40px;
            font-family: Arial,sans-serif;
            display: block;
            text-align: center;
            text-transform: uppercase;
            text-decoration: none;
            font-size: 40px;
            color: white;
        }


      img {
          display: block;
          margin: 0 auto;
      }



    </style>
</head>
<body>

<a class="login" href="http://localhost:8080/googlelogin">Zaloguj</a>
<a class="logout" href="main">Start Bez Logowania</a>

<img src="https://thumbor.sd-cdn.fr/wtvqeXqkR0A7PMZrUt3h9Q9_DDU=/770x515/cdn.sd-cdn.fr/wp-content/uploads/2019/03/Twitter-logo-illustration.jpg" alt="">




</body>
</html>