<!doctype html>
<html lang="pl-PL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Wylogowany</title>
    <style>

        body {
            background: #3aabef;
        }
        h1 {
            text-align: center;
            font-size: 36px;
            text-transform: uppercase;
            color: #e74c3c;

        }

        .main-menu {
            text-align: center;
            position: absolute;
            right: 200px;
            text-decoration: none;
            text-underline: none;

        }
    </style>
</head>
<body>
<h1>Zostałeś poprawnie wylogowany</h1>
<div class="main-menu"><a href="/main">Main Menu</a></div>
</body>
</html>